"""Phase 7 regression: strict structural gate rejects known-bad v2 puzzles.

The 25 Phase 7 puzzles were generated by the v2 lenient gate (which skips
1-2 tile partial stubs).  The strict gate from issue #30 should catch them,
proving the gate tightening works and will continue to work across refactors.

Easy and medium difficulty entries from the batch are used (10 puzzles total)
to keep the suite runtime reasonable; hard/expert/nightmare v2 generation can
take minutes per puzzle.

The ``phase7_easy_medium`` fixture is defined in ``conftest.py`` and shared
with ``test_heuristic_solver.py`` to avoid regenerating the same puzzles twice.
"""
from __future__ import annotations

import pytest

from solver.generator.gates.structural import check_no_trivial_extension
from solver.generator.puzzle_generator import PuzzleResult

pytestmark = pytest.mark.slow


# ---------------------------------------------------------------------------
# Happy path: generation succeeds and produces non-empty puzzles
# ---------------------------------------------------------------------------


def test_phase7_puzzles_generate_successfully(
    phase7_easy_medium: list[tuple[str, int, PuzzleResult]],
) -> None:
    """All 10 easy/medium Phase 7 v2 puzzles generate without error and have tiles."""
    assert len(phase7_easy_medium) == 10
    for difficulty, seed, result in phase7_easy_medium:
        assert result.rack, f"[{difficulty} seed={seed}] rack is empty"
        assert result.board_sets, f"[{difficulty} seed={seed}] board_sets is empty"
        assert result.generator_version == "v2.0.0", (
            f"[{difficulty} seed={seed}] expected v2.0.0, got {result.generator_version}"
        )


# ---------------------------------------------------------------------------
# Regression: strict gate catches v2 puzzles with partial stubs
# ---------------------------------------------------------------------------


def test_phase7_strict_gate_rejects_trivially_extensible_puzzles(
    phase7_easy_medium: list[tuple[str, int, PuzzleResult]],
) -> None:
    """Strict trivial-extension gate rejects >=6 of 10 Phase 7 v2 puzzles.

    The v2 lenient gate allows 1-2 tile stubs; the strict gate catches them.
    This regression ensures the gate remains tight across refactors: if
    someone weakens check_no_trivial_extension, these puzzles start passing
    and the test fails.
    """
    rejected: list[tuple[str, int, str]] = []
    for difficulty, seed, result in phase7_easy_medium:
        ok, reason = check_no_trivial_extension(result.rack, result.board_sets)
        if not ok:
            rejected.append((difficulty, seed, reason))

    assert len(rejected) >= 6, (
        f"Strict gate caught only {len(rejected)}/10 Phase 7 puzzles — "
        f"expected >=6. Rejected: {rejected}"
    )
