"""Phase 7 regression: strict structural gate rejects known-bad v2 puzzles.

The 25 Phase 7 puzzles were generated by the v2 lenient gate (which skips
1-2 tile partial stubs).  The strict gate from issue #30 should catch them,
proving the gate tightening works and will continue to work across refactors.

Easy and medium difficulty entries from the batch are used (10 puzzles total)
to keep the suite runtime reasonable; hard/expert/nightmare v2 generation can
take minutes per puzzle.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from solver.generator.gates.structural import check_no_trivial_extension
from solver.generator.puzzle_generator import PuzzleResult, generate_puzzle

pytestmark = pytest.mark.slow

_BATCH_PATH = (
    Path(__file__).parents[3]  # backend/
    / "solver/generator/calibration_batches/phase7_batch_v1.json"
)

_FAST_DIFFICULTIES = {"easy", "medium"}


def _load_fast_entries() -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = json.loads(_BATCH_PATH.read_text())["entries"]
    return [e for e in entries if e["difficulty"] in _FAST_DIFFICULTIES]


# ---------------------------------------------------------------------------
# Module-scoped fixture — generate easy+medium Phase 7 puzzles once per module
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def _phase7_results() -> list[tuple[str, int, PuzzleResult]]:
    """Generate 10 Phase 7 v2 puzzles (easy+medium) once for the whole module."""
    return [
        (
            e["difficulty"],
            e["seed"],
            generate_puzzle(e["difficulty"], seed=e["seed"], generator_version="v2"),
        )
        for e in _load_fast_entries()
    ]


# ---------------------------------------------------------------------------
# Happy path: generation succeeds and produces non-empty puzzles
# ---------------------------------------------------------------------------


def test_phase7_puzzles_generate_successfully(
    _phase7_results: list[tuple[str, int, PuzzleResult]],
) -> None:
    """All 10 easy/medium Phase 7 v2 puzzles generate without error and have tiles."""
    assert len(_phase7_results) == 10
    for difficulty, seed, result in _phase7_results:
        assert result.rack, f"[{difficulty} seed={seed}] rack is empty"
        assert result.board_sets, f"[{difficulty} seed={seed}] board_sets is empty"
        assert result.generator_version == "v2.0.0", (
            f"[{difficulty} seed={seed}] expected v2.0.0, got {result.generator_version}"
        )


# ---------------------------------------------------------------------------
# Regression: strict gate catches v2 puzzles with partial stubs
# ---------------------------------------------------------------------------


def test_phase7_strict_gate_rejects_trivially_extensible_puzzles(
    _phase7_results: list[tuple[str, int, PuzzleResult]],
) -> None:
    """Strict trivial-extension gate rejects >=6 of 10 Phase 7 v2 puzzles.

    The v2 lenient gate allows 1-2 tile stubs; the strict gate catches them.
    This regression ensures the gate remains tight across refactors: if
    someone weakens check_no_trivial_extension, these puzzles start passing
    and the test fails.
    """
    rejected: list[tuple[str, int, str]] = []
    for difficulty, seed, result in _phase7_results:
        ok, reason = check_no_trivial_extension(result.rack, result.board_sets)
        if not ok:
            rejected.append((difficulty, seed, reason))

    assert len(rejected) >= 6, (
        f"Strict gate caught only {len(rejected)}/10 Phase 7 puzzles — "
        f"expected >=6. Rejected: {rejected}"
    )
